name: prod
values:
  - key: baseUrl
    value: ''
  - key: weddingId
    value: ''
  - key: token
    value: ''
  - key: guestId
    value: ''
  - key: invitationId
    value: ''
  - key: invitationCode
    value: ''
  - key: giftId
    value: ''
color: 0
